'use strict';
const{test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
for(const n of ['core','character-motion','skin-rig'])vm.runInThisContext(fs.readFileSync(__dirname+'/../src/'+n+'.js','utf8'));
const R=DC.SkinRig;
const point=(m,p)=>[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];
const posed=(q,name,p)=>point(q.matrices.subarray(R.ids[name]*16,R.ids[name]*16+16),p);
test('body rig has explicit clavicles and three joints in each of ten digits',()=>{a.equal(R.bones.length,49);for(const k of ['L','R']){a.ok(R.ids['clavicle'+k]>=17);for(const f of ['thumb','index','middle','ring','little'])for(let j=0;j<3;j++)a.ok(Number.isInteger(R.ids[f+j+k]));}});
test('all rest skin matrices are identity, including fingers',()=>{a.equal(R.bones.length,49);const q=R.rest();for(let i=0;i<q.length;i++)a.ok(Math.abs(q[i]-(i%16%5===0?1:0))<.00001);});
test('body proportions expose the raised wrist and fitted shoulder landmarks',()=>{const bind=n=>R.bones[R.ids[n]][2];a.ok(bind('handR')[1]>.86);a.ok(bind('upperArmR')[0]<.22);a.ok(bind('pelvis')[1]>.92);});
test('grip closes fingers and does not change hand location',()=>{a.ok(R.fingers);const open=R.pose({grip:0},1),closed=R.pose({grip:1},1);for(const k of ['L','R']){a.deepEqual(Array.from(open.matrices.slice(R.ids['hand'+k]*16,R.ids['hand'+k]*16+16)),Array.from(closed.matrices.slice(R.ids['hand'+k]*16,R.ids['hand'+k]*16+16)));for(const f of R.fingers[k]){const p=posed(open,f.bones[2],f.tip),q=posed(closed,f.bones[2],f.tip);a.ok(Math.hypot(...p.map((v,i)=>v-q[i]))>.014,f.name);}}});
test('digit transforms remain finite through all gameplay poses and independent between actors',()=>{a.ok(R.fingers);let ref=R.pose({grip:.2,walk:1,moveSpeed:3},2),copy=Array.from(ref.matrices);for(const n of [{},{carry:'crate'},{seated:true},{crouch:1},{stagger:.8,dodge:.3},{y:.6,vy:-2},{grip:1},{reach:1,bodyLean:.4}]){const q=R.pose(n,2);a.equal(q.matrices.length,49*16);a.ok(Array.from(q.matrices).every(Number.isFinite));}a.deepEqual(Array.from(ref.matrices),copy);});
test('IK wrist movement propagates to all fingertip bones',()=>{a.ok(R.fingers);const n={x:0,z:0,yaw:0,handTargets:{R:{x:.35,y:1.22,z:.39}},grip:.5},q=R.pose(n,0),w=R.handPoint(q,n,'R');a.ok(Math.hypot(w.x-.35,w.y-1.22,w.z-.39)<.025);for(const f of R.fingers.R){const tip=posed(q,f.bones[2],f.tip);a.ok(Math.hypot(tip[0]-w.x,tip[1]+q.rootY-w.y,tip[2]-w.z)<.215,'finger left behind by IK '+f.name);}});
test('curling phalanges preserve their segment length',()=>{a.ok(R.fingers);for(const k of ['L','R'])for(const f of R.fingers[k])for(const grip of [0,.2,.7,1]){const q=R.pose({grip},1),b=f.bones[2],base=R.bones[R.ids[b]][2],a0=posed(q,b,base),a1=posed(q,b,f.tip);a.ok(Math.abs(Math.hypot(...a1.map((v,i)=>v-a0[i]))-Math.hypot(...f.tip.map((v,i)=>v-base[i])))<1e-5);}});
test('seated and carrying hands select deliberate grip rather than idle',()=>{a.ok(R.fingers);const idle=R.pose({},1),carry=R.pose({carry:'crate'},1),seat=R.pose({seated:true},1);a.ok(carry.grip>idle.grip);a.ok(seat.grip>idle.grip);a.ok(seat.grip<=1);});
test('GPU palette layout is derived from actual skeleton length',()=>{a.equal(R.paletteWidth,49*4);a.equal(R.paletteStride,49*16);const s=fs.readFileSync(__dirname+'/../src/cast-renderer.js','utf8');a.ok(!s.includes('slot*272'));a.ok(!s.includes('new Float32Array(68*128*4)'));});

test('closed thumb opposes the fingers rather than sticking sideways',()=>{for(const k of ['L','R']){const q=R.pose({grip:1},1),f=R.fingers[k].find(f=>f.name==='thumb'),tip=posed(q,f.bones[2],f.tip),w=R.handPoint(q,{},k);a.ok(tip[1]+q.rootY<w.y-.06,'thumb must fold below palm, '+k);a.ok(Math.abs(tip[2]-w.z)<.06);}});
