'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
for(const name of ['core','character-motion','skin-rig','crowd-geometry'])if(fs.existsSync(__dirname+'/../src/'+name+'.js'))vm.runInThisContext(fs.readFileSync(__dirname+'/../src/'+name+'.js','utf8'));
test('crowd reducer preserves valid weighted triangles and bounds',()=>{assert.equal(typeof DC.CrowdGeometry?.reduce,'function');const data=[];for(const p of [[0,0,0],[1,0,0],[0,1,0]])data.push(...p,0,0,1,0,0,0,0,0,0,1,0,0,0);const out=DC.CrowdGeometry.reduce(new Float32Array(data),.04);assert.equal(out.length,48);assert.ok(DC.SkinRig.validate(out));});
test('duplicate tiny triangles collapse rather than exploding',()=>{assert.ok(DC.CrowdGeometry);const data=[];for(const p of [[0,0,0],[.001,0,0],[0,.001,0]])data.push(...p,0,0,1,0,0,0,0,0,0,1,0,0,0);assert.equal(DC.CrowdGeometry.reduce(new Float32Array(data),.05).length,0);});
test('seated transition has no discontinuous change in body scale',()=>{const a=DC.SkinRig.pose({seated:true,seatBlend:.001},0),b=DC.SkinRig.pose({seated:true,seatBlend:0},0);assert.ok(Math.abs(a.scale-b.scale)<.001);assert.equal(a.scale,1);});
test('two-bone arm contact targets are reached without NaN',()=>{assert.equal(typeof DC.SkinRig.handPoint,'function');const n={x:8,z:-7,yaw:.4,handTargets:{R:{x:8.4,y:1.13,z:-6.65}}};const q=DC.SkinRig.pose(n,0),p=DC.SkinRig.handPoint(q,n,'R');assert.ok(Math.hypot(p.x-n.handTargets.R.x,p.y-n.handTargets.R.y,p.z-n.handTargets.R.z)<.025);});
test('impossible arm goal clamps to reach without stretching',()=>{assert.ok(DC.SkinRig.handPoint);const n={x:0,z:0,yaw:0,handTargets:{L:{x:999,y:500,z:600}}},q=DC.SkinRig.pose(n,0),p=DC.SkinRig.handPoint(q,n,'L');assert.ok([p.x,p.y,p.z].every(Number.isFinite));assert.ok(Math.hypot(p.x+.2295,p.y-1.43,p.z)<.64);});
test('blink envelope is bounded, deterministic and staggered across actors',()=>{assert.equal(typeof DC.SkinRig.blink,'function');assert.equal(DC.SkinRig.blink(.085,0),1);assert.equal(DC.SkinRig.blink(.4,0),0);assert.notEqual(DC.SkinRig.blink(.085,0),DC.SkinRig.blink(.085,.333));for(let t=-1;t<20;t+=.013){const v=DC.SkinRig.blink(t,.62);assert.ok(v>=0&&v<=1);assert.equal(v,DC.SkinRig.blink(t,.62));}});
