"""Captured from the shipped WebGL renderer. Prepared camera/positions, no image generation."""
from pathlib import Path
import os,json,hashlib,sys
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1];Q=R/'qa/v019';os.environ.setdefault('DISPLAY',':99')
mode=sys.argv[1]if len(sys.argv)>1 else 'gauss';html=(Path(os.environ.get('DC_BASELINE_HTML',str(R/'assets/baseline-v018.html'))) if '--before' in sys.argv else R/'index.html').read_text();errors=[]
fixture="""(()=>{window.testStore=new Map([['distrito-cero:settings:v1',JSON.stringify({quality:'balanced',rain:false,bloom:true,sound:false})]]);Object.defineProperty(window,'localStorage',{value:{getItem:k=>testStore.get(k)||null,setItem:(k,v)=>testStore.set(k,String(v)),removeItem:k=>testStore.delete(k)}});})();"""
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=False,args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']);p=b.new_page(viewport={'width':1120,'height':740});p.on('pageerror',lambda e:errors.append(str(e)));p.set_content(html.replace('<script>','<script>'+fixture,1),timeout=90000);p.wait_for_function('!!window.DC_APP',timeout=90000);p.evaluate('DC_APP.renderer.humanReady');p.evaluate('window.requestAnimationFrame=()=>0');p.wait_for_timeout(100);p.click('#start');p.click('#commitCreator');p.click('#dismissTutorial')
 p.evaluate('''mode=>{const a=DC_APP,s=a.sim;s.free=true;s.time=12;s.peds.forEach(n=>n.hidden=true);s.cars.forEach((c,i)=>Object.assign(c,{x:-300,z:-250-i*5,parked:true,speed:0}));Object.assign(s.player,{x:4,z:36,yaw:0,y:0,car:null,walk:0,moveSpeed:0,health:100});s.equipWeapon(mode==='optics'?'binoculars':mode==='emp'?'emp':mode==='reload'?'rifle':mode);s.equipmentStep(.02,{});a.renderer.daylight=.63;a.renderer.rain=0;a.renderer.camera.yaw=0;a.renderer.camera.weaponPitch=-.027;s.equipment.aimWeight=1;s.equipment.aiming=true;s.equipment.pitch=-.027;if(s.equipment.handling){s.equipment.handling.ready=1;s.equipment.handling.kick=0;}
  if(mode==='gauss')s.equipment.charge=.86;
  if(mode==='emp'){Object.assign(s.cars[1],{x:3,z:43,yaw:-.4,police:true,stolen:false,health:100});Object.assign(s.cars[2],{x:-4,z:46,yaw:.6,health:100});s.pulseEMP();s.weaponEffects.forEach(f=>f.life=.86);}
  if(mode==='reload'){s.equipment.ammo.rifle.loaded=10;s.reloadWeapon();s.equipment.reloading=.95;}
  if(mode==='optics'){Object.assign(s.cars[1],{x:4,z:75,yaw:.1,police:true});s.equipment.zoom=1;s.equipment.aiming=true;a.renderer.camera.weaponPitch=-.022;a.renderer.updateCamera(s,0);s.equipment.ray={origin:a.renderer.camera.eye.slice(),direction:DC.normalize(a.renderer.camera.target.map((v,i)=>v-a.renderer.camera.eye[i]))};}
  a.updateUI(performance.now());a.toastQueue=[];a.toastUntil=0;document.getElementById('toast').classList.remove('visible');document.getElementById('chapter').classList.remove('visible');document.getElementById('tutorial').hidden=true;
  if(mode!=='optics'){document.getElementById('opticsOverlay').hidden=true;document.body.classList.remove('optic-view');a.renderer.equipmentView=false;a.renderer.camera.eye=mode==='emp'?[12,5.0,30]:[5.70,1.85,37.80];a.renderer.camera.target=mode==='emp'?[2,1,43]:[4.04,1.26,36.28];a.renderer.fovOverride=mode==='emp'?1.02:.57;}
  a.renderer.frame=0;a.renderer.lightVP=null;a.renderer.render(s);window.captureInfo={mode,gl:a.renderer.gl.getError(),stats:a.renderer.equipmentStats,geometryKeys:Object.keys(a.renderer.meshes).filter(k=>k.startsWith('equip_')).length};}''',mode)
 p.screenshot(path=str(Q/(('before-' if '--before' in sys.argv else 'review-')+mode+'.png')),timeout=90000);info=p.evaluate('captureInfo');(Q/(('before-' if '--before' in sys.argv else 'review-')+mode+'.json')).write_text(json.dumps({'html':hashlib.sha256(html.encode()).hexdigest(),'errors':errors,**info},indent=2));print(info,flush=True);b.close()
