'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
for(const n of ['core','world','frontier-world','police','simulation','dynamics','interactions','frontier-simulation','occupancy','appearance','character-fit','weapon-handling','equipment','equipment-simulation','save-store','character-motion','skin-rig'])vm.runInThisContext(fs.readFileSync('src/'+n+'.js','utf8'));
DC.Audio=class{};DC.App=class{};
vm.runInThisContext(fs.readFileSync('src/equipment-ui.js','utf8'));
function setup(){const sim=new DC.Simulation(new DC.World());sim.equipment.selected='rifle';return sim;}
test('switching equipment initializes its lowered pose before the first frame',()=>{const s=setup();s.equipment.handling={item:'rifle',ready:1};s.equipWeapon('gauss');const m=DC.Equipment.mount(s);a.equal(m.ready,0);a.equal(s.equipment.handling.item,'gauss');DC.WeaponHandling.step(s,1/120);a.ok(s.equipment.handling.ready>0&&s.equipment.handling.ready<.1);});
test('closing a selector preserves only the visible aim blend, never trigger state',()=>{const sim=setup(),snapshot=DC.Equipment.snapshot(sim.equipment),app={sim,arsenalReturn:'play',renderer:{frozenHandling:{equipment:{selected:'rifle',aimWeight:.85,trigger:true,charge:.9}}},setMode(mode){this.mode=mode;this.renderer.frozenHandling=null;sim.cancelEquipment();}};DC.EquipmentApp.prototype.closeArsenal.call(app);a.equal(sim.equipment.aimWeight,.85);a.equal(sim.equipment.trigger,false);a.equal(sim.equipment.charge,0);a.equal(sim.equipment.aiming,false);a.equal(app.mode,'play');a.deepEqual(DC.Equipment.snapshot(sim.equipment),snapshot);});
test('closing after a different selection does not inherit the old pose',()=>{const sim=setup(),app={sim,arsenalReturn:'play',renderer:{frozenHandling:{equipment:{selected:'gauss',aimWeight:1}}},setMode(){this.renderer.frozenHandling=null;sim.cancelEquipment();}};DC.EquipmentApp.prototype.closeArsenal.call(app);a.equal(sim.equipment.aimWeight,0);});
test('pause-return does not retain an armed input or visual aiming request',()=>{const sim=setup(),app={sim,arsenalReturn:'pause',renderer:{frozenHandling:{equipment:{selected:'rifle',aimWeight:1}}},setMode(mode){this.mode=mode;this.renderer.frozenHandling=null;sim.cancelEquipment();}};DC.EquipmentApp.prototype.closeArsenal.call(app);a.equal(sim.equipment.aimWeight,0);a.equal(app.mode,'pause');});
test('restoring an equipped save initializes presentation before the first rendered frame',()=>{const s=setup(),copy=s.serialize();a.ok(s.restore(copy));a.equal(s.equipment.handling?.item,'rifle');a.equal(DC.Equipment.mount(s).ready,0);a.deepEqual(DC.Equipment.snapshot(s.equipment),copy.equipment);});
