"""High-quality editor captures. Real renderer, controlled time, no appearance retouching."""
from pathlib import Path
import os,json,hashlib
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1];O=R/'qa/v011';os.environ.setdefault('DISPLAY',':99')
FIX='''(()=>{let d=new Map([['distrito-cero:settings:v1',JSON.stringify({quality:'eco',sound:false,rain:false,bloom:false})]]);Object.defineProperty(window,'localStorage',{value:{getItem:k=>d.get(k)||null,setItem:(k,v)=>d.set(k,v)}});})();'''
report={'captures':[],'errors':[],'sha256':hashlib.sha256((R/'index.html').read_bytes()).hexdigest()}
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=False,args=['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']);p=b.new_page(viewport={'width':1280,'height':840});p.on('pageerror',lambda e:report['errors'].append(str(e)));p.set_content((R/'index.html').read_text().replace('<script>','<script>'+FIX,1),timeout=90000);p.wait_for_function('!!window.DC_APP',timeout=90000);p.evaluate('DC_APP.renderer.humanReady');p.evaluate('window.drawReal=DC_APP.renderer.render.bind(DC_APP.renderer);DC_APP.renderer.render=()=>{};DC_APP.loop=()=>{}');p.click('#start');p.evaluate('DC_APP.creator.animate=false;DC_APP.creator.elapsed=1;DC_APP.renderer.quality="high";DC_APP.fitCreator()')
 for i,label in enumerate(['Alex','Luz','Noa','Río']):
  p.click('[data-preset="'+str(i)+'"]');p.fill('#characterName',label);p.fill('#newSaveName',label+' · Distrito Cero');p.locator('#creatorForm').evaluate('e=>e.scrollTop=0');p.evaluate('DC.IdentityApp.prototype.loop.call(DC_APP,performance.now());drawReal(DC_APP.creator.preview)');p.screenshot(path=str(O/f'editor-style-{i}.png'),timeout=60000);info=p.evaluate('({look:DC_APP.creator.look,rect:document.getElementById("world").getBoundingClientRect().toJSON(),gl:DC_APP.renderer.gl.getError(),stats:DC_APP.renderer.castStats})');report['captures'].append({'file':f'editor-style-{i}.png',**info});print(i,info['gl'],flush=True)
  if i==1:
   p.click('#previewFrame');p.evaluate('DC.IdentityApp.prototype.loop.call(DC_APP,performance.now());drawReal(DC_APP.creator.preview)');p.screenshot(path=str(O/'editor-face-final.png'),timeout=60000);p.click('#previewFrame')
 p.click('#closeCreator');p.evaluate('DC_APP.renderer.quality="eco";DC_APP.renderer.resize()');p.click('#freeRoam');p.fill('#characterName','Noa');p.fill('#newSaveName','Noa · Rumbo a Nueva Aurora');p.click('[data-preset="2"]');p.click('#commitCreator');p.click('#dismissTutorial');p.keyboard.press('Escape');p.click('#pauseSaves');p.evaluate('DC_APP.getStore().create("Alex · La llamada",new DC.Simulation(new DC.World(333)).serialize(),{activate:false});DC_APP.paintLibrary()');p.fill('#copySaveName','Noa · La otra ruta');p.click('#librarySaveCopy');p.evaluate('drawReal(DC_APP.sim)');p.screenshot(path=str(O/'library-final.png'),timeout=60000);report['finalGl']=p.evaluate('DC_APP.renderer.gl.getError()');(O/'editor-captures.json').write_text(json.dumps(report,indent=2));b.close()
