'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={};vm.createContext(context);const file='tools/qa/manual_frames.js';if(fs.existsSync(file))vm.runInContext(fs.readFileSync(file,'utf8'),context);
function app(){let draws=0,finishes=0;const r={frame:3,disposed:false,resources:{disposed:false,stats:()=>({total:20})},gl:{lost:false,NO_ERROR:0,isContextLost(){return this.lost;},finish(){finishes++;},getError:()=>0},render(){draws++;this.frame++;}};return{renderer:r,mode:'play',graphics:{state:'ready'},sim:{},frameRequest:5,stopFrame(){this.frameRequest=null;},counts:()=>[draws,finishes]};}
test('manual capture stops only the application frame chain, leaving browser RAF intact',()=>{const a=app(),native=()=>7;context.requestAnimationFrame=native;context.DC_MANUAL_FRAMES.start(a);assert.equal(a.frameRequest,null);assert.equal(context.requestAnimationFrame,native);});
test('a manual draw waits for the actual GPU command stream and verifies the frame',()=>{const a=app();context.DC_MANUAL_FRAMES.draw(a);assert.deepEqual(a.counts(),[1,1]);});
test('loss before draw fails loudly without a retry or a stale render',()=>{const a=app();a.renderer.gl.lost=true;assert.throws(()=>context.DC_MANUAL_FRAMES.draw(a),/DC_QA_GRAPHICS.*lost/);assert.deepEqual(a.counts(),[0,0]);});
test('retired generation and unfinished recovery are not accepted as rendered evidence',()=>{for(const kind of ['disposed','recovery']){const a=app();if(kind==='disposed')a.renderer.disposed=true;else a.graphics.state='restoring';assert.throws(()=>context.DC_MANUAL_FRAMES.draw(a),/DC_QA_GRAPHICS/);assert.deepEqual(a.counts(),[0,0]);}});
test('a loss during GPU completion is not relabeled as a passing frame',()=>{const a=app();a.renderer.gl.finish=()=>{a.renderer.gl.lost=true;};assert.throws(()=>context.DC_MANUAL_FRAMES.draw(a),/DC_QA_GRAPHICS.*lost/);assert.equal(a.counts()[0],1);});
test('GL errors and a no-op renderer cannot pass the capture gate',()=>{const a=app();a.renderer.gl.getError=()=>1282;assert.throws(()=>context.DC_MANUAL_FRAMES.draw(a),/1282/);const b=app();b.renderer.render=()=>false;assert.throws(()=>context.DC_MANUAL_FRAMES.draw(b),/frame did not advance/);});
test('ordinary renderer errors are preserved instead of retried or swallowed',()=>{const a=app();a.renderer.render=()=>{throw Error('bad mesh');};assert.throws(()=>context.DC_MANUAL_FRAMES.draw(a),/bad mesh/);assert.deepEqual(a.counts(),[0,0]);});
