/* Independent contact checks use real weighted skin triangles, not just IK pivots. */
'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
for(const n of ['core','world','frontier-world','police','simulation','dynamics','interactions','frontier-simulation','occupancy','appearance','character-fit','weapon-handling','equipment','equipment-simulation','character-motion','skin-rig','dual-quaternion','hero-asset'])vm.runInThisContext(fs.readFileSync('src/'+n+'.js','utf8'));
const D=DC,part=D.HeroAsset.parts.find(p=>p.name==='skin'),data=Buffer.from(part.data,'base64');
const sub=(a,b)=>a.map((v,i)=>v-b[i]),distance=(a,b)=>Math.hypot(...sub(a,b));
function vertex(i){const j=i*24;return{p:[0,2,4].map(k=>data.readInt16LE(j+k)/1e4),j:[16,17,18,19].map(k=>data[j+k]),w:[20,21,22,23].map(k=>data[j+k]/255)};}
function sample(k){const side=k==='R'?1:-1,o=[side*.20,.836,0],dir=[side,0,0];let hit=null;for(let i=0;i<part.vertices;i+=3){const tri=[vertex(i),vertex(i+1),vertex(i+2)];if(tri.some(v=>v.p[0]*side<.23))continue;const e1=sub(tri[1].p,tri[0].p),e2=sub(tri[2].p,tri[0].p),h=D.cross(dir,e2),det=D.dot(e1,h);if(Math.abs(det)<1e-9)continue;const v0=sub(o,tri[0].p),u=D.dot(v0,h)/det,q=D.cross(v0,e1),v=D.dot(dir,q)/det,t=D.dot(e2,q)/det;if(u<0||v<0||u+v>1||t<0)continue;if(!hit||t<hit.t)hit={tri,bary:[1-u-v,u,v],t};}a.ok(hit,'intersects '+k+' palm');return hit;}
const samples={L:sample('L'),R:sample('R')};
function skinPoint(q,n,k){const dq=D.DualQuaternion.pack(q.matrices),hit=samples[k],v=hit.tri.map(v=>D.DualQuaternion.transform(dq,v.p,v.j,v.w)),out=[0,1,2].map(j=>v.reduce((s,p,i)=>s+p[j]*hit.bary[i],0));const c=Math.cos(n.yaw),s=Math.sin(n.yaw);return[n.x+out[0]*c+out[2]*s,out[1]+q.rootY,n.z-out[0]*s+out[2]*c];}
test('neutral palm reference lies within two millimetres of real quantized skin',()=>{for(const k of ['L','R']){const b=D.SkinRig.bones[D.SkinRig.ids['hand'+k]][2],anchor=b.map((v,i)=>v+D.WeaponHandling.palmLandmark(k)[i]),v=[0,1,2].map(j=>samples[k].tri.reduce((s,v,i)=>s+v.p[j]*samples[k].bary[i],0));a.ok(distance(anchor,v)<.002);}});
test('actual DQ-deformed palmar triangles stay close to object contact anchors',()=>{const s=new D.Simulation(new D.World());Object.assign(s.player,{x:4,z:36,yaw:.8,car:null});s.time=2;let max=0;for(const id of ['pistol','rifle','gauss','emp','binoculars','baton','grenade'])for(const aim of [0,1])for(const progress of[0,.32,.52,.72]){s.equipment.selected=id;s.equipment.aimWeight=aim;s.equipment.reloading=progress?(1-progress)*(D.Equipment.get(id).reload||0):0;const m=D.Equipment.mount(s),n=D.WeaponHandling.actor(s.player,m,s.equipment),q=D.SkinRig.pose(n,s.time);for(const k of Object.keys(m.hands)){const err=distance(skinPoint(q,n,k),[m.palmContacts[k].x,m.palmContacts[k].y,m.palmContacts[k].z]);max=Math.max(max,err);a.ok(err<.013,`${id} ${k} ${progress}: ${err}`);}}console.log('realSkinPalmMaxError',max);});
